Feat/billing
stranded-in-python/movix-admin pull request #26
Opened 2023-10-03 16:44 UTC by dogbusiness

Добавил биллинг. Со схемой для подписок неясненько

2023-10-04 08:51 UTC, SBKubric requested changes
Отличный старт)

Нужно поправить модели, добавить описания, убрать миграции.
Ещё надо добавить таблицу подписок и аккаунт, они есть в movix-subscription-api

После этого можно сделать вьюшку для аккаунта. Было бы хорошо добавить поиск по пользователю, его почте, и айдишникам всяким

2023-10-04 08:51 UTC, SBKubric commented on admin/billing/migrations/0001_initial.py
> +# Generated by Django 3.2 on 2023-10-03 16:27
Если ты подключаешься к чужой базе - зачем миграции? Миграции надо отключить для всех моделей, живущих не в админке.

2023-10-04 08:51 UTC, SBKubric commented on admin/billing/models.py
> +        abstract = True
Надо добавить managed = False: https://docs.djangoproject.com/en/4.2/topics/db/models/#meta-inheritance

2023-10-04 08:51 UTC, SBKubric commented on admin/billing/admin.py
> +class InvoiceAdmin(admin.ModelAdmin):
Вместо того, чтобы регистрировать три отдельные админки для каждой сущности, правильнее, наверное, было бы сделать админку для юзера, и внутри неё отображать состояние подписки, а транзакции группировать под ними.

2023-10-04 16:35 UTC, yegres280 commented
Я учел правки, но сделать в точности как ты просишь не получится из-за связей.
Есть Account, у которого можно посмотреть статус (инлайн AccountStatus) и платежи (инлайн Invoice). Оставил модель платежей и сделал там инлайн на возвраты и транзакции, так как прямой связки Account и Refund, AcqLog не имеют.

Кстати, у меня в инвойсах есть колонка user_id, но, я так понимаю, правильнее назвать ее account_id.

2023-10-05 12:42 UTC, SBKubric requested changes
Две проблемы,  managed = False не везде проставлено, и есть возможность редактирования транзакций

2023-10-05 12:42 UTC, SBKubric commented on admin/billing/models.py
> +        abstract = True
Добавить managed = False ко всем моделям

2023-10-05 12:42 UTC, SBKubric commented on admin/billing/admin.py
> +    list_display = ["user_id", "subscription"]
Надо отключить возможность записи, оставив только просмотр для сущностей

2023-10-05 15:22 UTC, SBKubric approved these changes
LGTM

2023-10-05 15:22 UTC, merged